apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: EKS-course-clus
  region: us-east-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 3
    ssh: # use existing EC2 key
      publicKeyName: eks-learn
  - name: scale-east1a
    instanceType: t3.large
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-workload
      instance-type: onDemand
    ssh: 
      publicKeyName: eks-learn
  - name: scale-east1fa
    instanceType: t3.large
    desiredCapacity: 1
    maxSize: 10
    availabilityZones: ["us-east-1f", "us-east-1a"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateful-workload
      instance-type: onDemand
    ssh:
      publicKeyName: eks-learn
  - name: scale-spot
    desiredCapacity: 1
    maxSize: 10
    instancesDistribution:
      instanceTypes: ["t2.small", "t3.small"]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
    availabilityZones: ["us-east-1a", "us-east-1f"]
    iam:
      withAddonPolicies:
        autoScaler: true
    labels:
      nodegroup-type: stateless-workload
      instance-type: spot
    ssh: 
      publicKeyName: eks-learn

availabilityZones: ["us-east-1a", "us-east-1f"]
 

