kind: Deployment
apiVersion: apps/v1
metadata:
  name: efs-provisioner
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: efs-provisioner
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: efs-provisioner
    spec:
      containers:
        - name: efs-provisioner
          image: quay.io/external_storage/efs-provisioner:v0.1.0
          env:
            - name: FILE_SYSTEM_ID
              value: fs-b9335a0d 
            - name: AWS_REGION
              value: us-east-1
            - name: PROVISIONER_NAME
              value: eks-course/aws-efs
          volumeMounts:
            - name: pv-volume
              mountPath: /persistentvolumes
      volumes:
        - name: pv-volume
          nfs:
            server: fs-b9335a0d.efs.us-east-1.amazonaws.com
            path: /

